# Generated by Django 3.2.6 on 2021-09-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactus',
        ),
    ]
