# Generated by Django 3.2.6 on 2021-09-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_rename_contact_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
