# Generated by Django 3.2.6 on 2021-12-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
