# Generated by Django 3.2.6 on 2021-12-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
